### ISSUE TITLE
Feature request: summary of failing test cases

### ISSUE THREAD

**Issue by killkrt** [doctest/doctest#261]
It would be great to have, at the end of the report dumped to the standard output, a list with all test cases that are failing, just to have a quick summary avoiding to open the (in my case) the big report and scroll pages of logs to find which test cases are failing.

Maybe could be disabled by default and activable via some flag/option. 

Thank you.

**Comment by onqtam** [comment]
This could perhaps be satisfied with a compact reporter:

https://github.com/onqtam/doctest/issues/75

**Comment by killkrt** [comment]
Uhm... Not sure what a compact reporter will include, anyway basically it would be great if it could include also the list of the failing test case, just their name.

Thank you for your great job!

**Comment by cdeln** [comment]
This is the default behavior now isn't?

This test

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("a") {
    CHECK(0 == 0);
}

TEST_CASE("b") {
    CHECK(0 == 1);
}

TEST_CASE("c") {
    CHECK(0 == 2);
}
```

produce

```console
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
main.cpp:8:
TEST CASE:  b

main.cpp:9: ERROR: CHECK( 0 == 1 ) is NOT correct!
  values: CHECK( 0 == 1 )

===============================================================================
main.cpp:12:
TEST CASE:  c

main.cpp:13: ERROR: CHECK( 0 == 2 ) is NOT correct!
  values: CHECK( 0 == 2 )

===============================================================================
[doctest] test cases: 3 | 1 passed | 2 failed | 0 skipped
[doctest] assertions: 3 | 1 passed | 2 failed |
[doctest] Status: FAILURE!
```

You can filter out the names of the failing test cases with `grep 'TEST CASE'`.

I would say this is resolved. Please let me know if I misunderstood anything and this is now the case.

**Comment by bilderbuchi** [comment]
> I would say this is resolved. Please let me know if I misunderstood anything and this is now the case.

AFAICT this is not resolved. To see why, make your MWE test cases produce 3 screens of output -- in effect you'll only see the tail end of test case `c`'s output, and the
```
===============================================================================
[doctest] test cases: 3 | 1 passed | 2 failed | 0 skipped
[doctest] assertions: 3 | 1 passed | 2 failed |
[doctest] Status: FAILURE!
```
part. 
This issue is about that this final section should also contain something like
```
[doctest] failed test cases:
[doctest] b
[doctest] c
```
